---

- name: Get all wordpress hosts into an in memory group
  set_fact:
    wordpress_hosts: "{{ groups['user-vpc_wordpress'] }}"

- name: "Sync data with the wordpress instances (direction {{ sync_action }})"
  include: "{{ sync_action }}.yml"

- name: Restart docker-compose services
  shell: "docker-compose -f /etc/docker-compose/wordpress/docker-compose.yml restart"
  delegate_to: "{{ item }}"
  with_items: "{{ wordpress_hosts }}"


