---

- name: Get all wordpress hosts into an in memory group
  set_fact:
    wordpress_hosts: "{{ groups['user-vpc_wordpress'] }}"

- name: Get latest wp-contents/uploads data
  git:
    clone: yes
    depth: 1
    dest: "{{ playbook_dir }}/uploads-content"
    repo: "git@gitlab.service.opg.digital:sirius/help-and-guidance-content.git"
    version: "master"
    accept_hostkey: yes

- name: "Sync data with the wordpress instances (direction {{ sync_action }})"
  include: "{{ sync_action }}.yml"


- block:
    - name: Modify the sql script locally to use the domain name
      shell: sed -e -i "'s/PLACEHOLDERDOMAIN/{{ "wordpress." + target + "." + domain  }}/g' {{ playbook_dir }}/uploads-content/wordpress.sql"
      delegate_to: localhost

    - name: Load the query into the ad_hoc sql variable
      set_fact:
        query_string: "{{ lookup( playbook_dir + '/uploads-content/wordpress.sql' )}}"
      delegate_to: localhost

      #Set some vars and magic
    - name: Execute the sql file
      include_role:
        name: ec2-rds
        tasks_from: mysql-query


  when: overwrite_db is defined and overwrite_db


