---

- name: Confirm we have a plugins.yml file
  stat: "{{ playbook_dir }}/uploads-content/plugins.yml"
  register: plugin_st

- block:
    - name: Set our base download path
      set_fact:
        base_wp_url: "https://downloads.wordpress.org/plugin/"

    - name: Load our list of plugins
      include_vars:
        file: "{{ playbook_dir }}/uploads-content/plugins.yml"
        name: wordpress_plugins

    - name: Retrieve our plugins from the wordpress servers
      unarchive:
        src:  "{{ base_wp_url + item }}"
        dest: "{{ playbook_dir }}/uploads-content/plugins/"
        remote_src: true
      with_items: wordpress_plugins.plugins

  when: plugin_st.exists and plugin_st.isreg