---

# To change in ansible 2.3 to use archive
- name: Compress our local content
  shell: "tar -czf {{ playbook_dir }}/uploads.tar.gz uploads"
  args:
    chdir: "{{ playbook_dir }}/uploads-content/"
  run_once: yes

- name: Upload and unpack our artefacts
  include: unpack.yml
  loop_control:
    loop_var: remote_wp
  with_items: "{{ groups['user-vpc_wordpress'] }}"