---

- name: Remove metric alarms
  ec2_metric_alarm:
    name: "{{ asg_instance.name + '-' + opg_data.stack + '-' + scaling_policy_data.name + '-metric-alarm' }}"
    state: absent
  with_items: "{{ asg_instance.scaling_policies.metric_alarms|default([]) }}"
  loop_control:
    loop_var: scaling_policy_data

- name: Configure Scaling Policy
  ec2_scaling_policy:
    name: "{{ asg_instance.name + '-' + opg_data.stack + '-' + scaling_policy_data.name }}"
    asg_name: "{{ asg_instance.name }}-{{ opg_data.stack }}"
    state: absent
