---

#- name: Create public-facing route53 entry
#  route53:

- name: Retrieve our related elb
  action:
    module: ec2_elb_facts
    names:
      - "{{ item.origin }}"
  register: elb_data

- name: Ensure we have our elb info
  assert:
    that: elb_data.elbs.0.dns_name is defined

- name: Retrieve our shit
  cloudfront_facts:
    distribution: true
    distribution_id: "EBPWV3WFX4R83"
  register: cf_facts

- fail: msg="{{ cf_facts }}"
- name: Create distribution with custom certificate
  cloudfront:
    type: distribution
    state: present
    wait_for_deployed: yes
    policy: "{{ lookup('template', 'distribution.json') | to_json }}"
  register: cdn_distro

- name: Create cname for domain
  route53:
    zone: "{{ opg_data.domain }}"
    state: present
    zone: "{{ cdn_distro.result.distribution.domain_name }}"
    record: " {{ item.cname }}"
    type: CNAME
    overwrite: yes
    ttl: 300


#- name: Create distribution with custom certificate
#  cloudfront:
#    type: origin_access_id
#    state: present
#    policy: "templates/origin_access.json"
