galaxy_info:
  author: UKGov/Ministry of Justice/Office of the Public Guardian
  description: An Ansible role that bakes an AMI instance
  company: UKGov/Ministry Of Justice/Office of the Public Guardian

  license: license MIT

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
    - EC2

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
