---

- name: Set bucket name (no suffix)
  set_fact:
    bucket_name: "{{ bucket_data.name }}"
  when:  use_s3_suffix is not defined or not use_s3_suffix

- name: Set bucket name (with suffix)
  set_fact:
    bucket_name: "{{ bucket_data.name }}-{{ opg_data.stack }}"
  when:  use_s3_suffix is defined and use_s3_suffix

- name: Display bucketname message
  debug:
    msg: "Removing S3 bucket {{bucket_name}}"

- name: Destroy S3 bucket
  s3_bucket:
    name: "{{ bucket_name }}"
    state: absent
    force: true
