---

  - name: Create iam delagatee role
    iam_role:
      name: "{{ iam_scaling_policy_name }}-{{ target }}"
      state: present
      assume_role_policy_document: "{{ lookup('template', 'dynamodb-trust-relationship.json.j2') }}"
    register: dynamodb_iam_role

  - name: Create truse relationship policy
    iam_

# see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.CLI.html
# create role
# create policy
# attach policy to role
# for dynamodb created if name in scaling_policies
# register scalable target as table
#  aws application-autoscaling register-scalable-target \
#    --service-namespace dynamodb \
#    --resource-id "table/TestTable" \
#    --scalable-dimension "dynamodb:table:WriteCapacityUnits" \
#    --min-capacity 5 \
#    --max-capacity 10 \
#    --role-arn roleARN
#
#