---

- name: Remove the the write scaling policy
  command: "aws application-autoscaling delete-scaling-policy
            --service-namespace dynamodb
            --resource-id 'table/{{ dynamodb_scaling_policy.name }}-{{ target }}'
            --scalable-dimension 'dynamodb:table:WriteCapacityUnits'
            --policy-name '{{ dynamodb_scaling_policy.name }}-{{ target }}-write-scaling'"
  ignore_errors: True
  register: dynamodb_write_scaling_policy

- name: Remove the the read scaling policy
  command: "aws application-autoscaling delete-scaling-policy
            --service-namespace dynamodb
            --resource-id 'table/{{ dynamodb_scaling_policy.name }}-{{ target }}'
            --scalable-dimension 'dynamodb:table:ReadCapacityUnits'
            --policy-name '{{ dynamodb_scaling_policy.name }}-{{ target }}-read-scaling'"
  ignore_errors: True
  register: dynamodb_read_scaling_policy

- name: Deregister the dynamo table write capacity as a scalable target
  command: "aws application-autoscaling deregister-scalable-target
            --service-namespace dynamodb
            --resource-id 'table/{{ dynamodb_scaling_policy.name }}-{{ target }}'
            --scalable-dimension 'dynamodb:table:WriteCapacityUnits'"
  ignore_errors: True
  register: dynamodb_scalable_write_target

- name: Deregister the dynamo table read capacity as a scalable target
  command: "aws application-autoscaling deregister-scalable-target
            --service-namespace dynamodb
            --resource-id 'table/{{ dynamodb_scaling_policy.name }}-{{ target }}'
            --scalable-dimension 'dynamodb:table:ReadCapacityUnits'"
  ignore_errors: True
  register: dynamodb_scalable_write_target

- name: Delete policies from iam roles
  iam_policy:
    state: absent
    policy_name: 'scaling-policy-{{ dynamodb_scaling_policy.name }}-{{ target }}'
    iam_name: "scaling-role-{{ dynamodb_scaling_policy.name }}-{{ target }}"
    iam_type: role

- name: Remove the iam trust relationship role
  iam_role:
    name: "scaling-role-{{ dynamodb_scaling_policy.name }}-{{ target }}"
    state: absent
  register: dynamodb_iam_role
