---
- set_fact:
    ecs_clusters: "{{ app_data|rejectattr('ecs_cluster', 'undefined')|map(attribute='ecs_cluster')|list|unique }}"

- set_fact:
    typed_apps: "{{ app_data|rejectattr('type', 'undefined')|list }}"

- name: Create ECS apps
  include: ecs.yml
  with_items: "{{ typed_apps|selectattr('type','match','ecs')|list }}"
  loop_control:
    loop_var: appdata
  tags:
    - ecs
