---
- name: Setup facts for ecs service
  set_fact:
    has_elb: "{{ appdata.elb is defined }}"

- name: Check that there is a container defintion
  assert:
    that:
      - appdata.containers is defined
      - appdata.containers|list|count > 0

- name: Configure ECS IAM objects
  include: iam.yml

- block:
    - name: Setup facts for app ELB
      set_fact:
        elbdata: "{{ appdata.elb }}"
        elb_name: "{{ appdata.name }}"

    - name: Create ELB and related objects
      include: 'ecs-elb.yml'
  when: has_elb

- name: Create instances and related objects
  include: 'ecs-service.yml'
