---

- block:
    - block:
        - name: Create security group for rds (defined route)
          ec2_group:
            name: "{{ rds_instance_data.rds_sg.name }}-{{ target }}"
            description: "{{ rds_instance_data.rds_sg.desc }}"
            rules: "{{ rds_instance_data.rds_sg.ruleset | rules_from_dict(client_sg_ids.security_groups, rds_instance_data.rds_sg.client_sg) }}"
            rules_egress: []
            vpc_id: "{{ vpc_id }}"
          register: rds_security_group_1

      when: rds_instance_data.rds_sg.client_sg is defined

    - block:
        - name: Create security group for rds (undefined route)
          ec2_group:
            name: "{{ rds_instance_data.rds_sg.name }}"
            description: "{{ rds_instance_data.rds_sg.desc }}"
            rules: "{{ rds_instance_data.rds_sg.ruleset | rules_from_dict() }}"
            rules_egress: []
            vpc_id: "{{ vpc_id }}"
          register: rds_security_group_2

      when: rds_instance_data.rds_sg.client_sg is undefined

    - name: Add tags until 2.2
      ec2_tag:
        resource: "{{ rds_security_group_2.group_id | default(rds_security_group_1.group_id) }}"
        state: present
        tags: "{% set sg_group_name = rds_instance_data.rds_sg.name + '-' + target %}{{ vpc.env_tags | combine( {'Name': sg_group_name} )}}"

  when: rds_instance_data.rds_sg is defined
