---

- name: Destroy RDS instances for stack
  rds:
    command: delete
    instance_name: "{{ rds_instance.db_name + '-' + opg_data.stack  }}"
    snapshot: "{{ rds_instance.snapshot_name }}"
  register: rds_destroy

- block:
  - name: Wait until RDS instance is destroyed
    rds:
      command: facts
      instance_name: "{{ rds_instance.db_name + '-' + opg_data.stack }}"
    register: rds_instance_facts
    until: rds_instance_facts.instance.status != "deleting"
    retries: 30
    delay: 60
    when: rds_destroy|changed
  rescue:
    - debug:
        msg: "RDS instances do not exist"