---

#destroy rds resources
- block:
    - block:
      - name: Destroy rds instances
        include: destroy_rds_instance
        with_items: "{{ rds_instance|default([]) }}"
        loop_control:
          loop_var: rds_dbs

    - name: Destroy RDS parameter groups
      rds_param_group:
        name: '{{ item }}-db-params-{{ target }}'
        state: absent
      with_items:
        - postgres
        - mysql
      when: rds_dbs|default([])|count > 0
