---

- name: Destroy RDS instances for stack with snapshot (Default)
  rds:
    command: delete
    instance_name: "{{ rds_instance.db_name + '-' + opg_data.stack  }}"
    snapshot: "{{ rds_instance.db_name + '-' + opg_data.stack + '-final-snapshot-' + date_stamp.stdout }}"
  register: rds_destroy
  when: rds_instance.snapshot_instance is not defined or rds_instance.snapshot_instance

- name: Destroy RDS instances for stack without snapshot
  rds:
    command: delete
    instance_name: "{{ rds_instance.db_name + '-' + opg_data.stack  }}"
    snapshot: "{{ rds_instance.db_name + '-' + opg_data.stack + '-final-snapshot-' + date_stamp.stdout }}"
  register: rds_destroy
  when: rds_instance.snapshot_instance is defined and not rds_instance.snapshot_instance

- block:
  - name: Wait until RDS instance is destroyed
    rds:
      command: facts
      instance_name: "{{ rds_instance.db_name + '-' + opg_data.stack }}"
    register: rds_instance_facts
    until: rds_instance_facts.instance.status != "deleting"
    retries: 30
    delay: 60
    when: rds_destroy|changed
  rescue:
    - debug:
        msg: "RDS instances do not exist"