- block:
    - set_fact:
        nfs_host: "{{ groups['nfs-' + target][0] }}"
    - set_fact:
        nfs_launch_time: "{{ hostvars[nfs_host]['create_time'][0:19]|regex_replace('T|Z', ' ') }}"

    - name: Test that NFS server is older than 6 minutes
      shell: date +'%Y-%d-%m %H:%M:%S'
      register: nfs_ready
      until: ((nfs_ready.stdout|to_datetime) - (nfs_launch_time|to_datetime('%Y-%m-%d %H:%M:%S'))).total_seconds()|int > nfs_wait|default(360)
      retries: 10
      delay: 30

    - name: Ensure symlink nsfdata to data on NFS server
      file:
        src: '/data'
        dest: '/nfsdata'
        state: link
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true

    - name: Ensure template paths are created on NFS server
      file:
        state: directory
        follow: yes
        owner: 999
        path: "{{item.filepath | dirname}}"
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true
      with_items: "{{ appdata.nfs_templates }}"

    - name: Create templates on NFS
      template:
        src: "{{item.sourceTemplate}}"
        dest: "{{item.filepath}}"
        owner: 999
      with_items: "{{ appdata.nfs_templates }}"
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true

  when:
    - appdata.nfs_templates is defined
    - appdata.nfs_templates |count > 0
